#!/bin/bash
#This file uses code to analyse the Business Details file to help the user to find business(es) based upon search criteria
#Todo:  search for business(es) based upon any business information and display to the screen
#Todo: indent and comment on code for this functionality
echo "Thanks for trying to search for a business"
