#!/bin/bash
#main script file with menu structure
function emailBusiness
{
   while [ "$ReplyEmail" != "q" ] #if q is selected then the while condition is met and the loop ends
do
  cat <<EOF
 
  Email menu
  (1) "Email a single Business"
  (2) "Email all Businesses"
  (q) "quit emailing" 
  Enter a selection:
EOF
  #The quit option was given for ergonomics
 read  ReplyEmail
 case "$ReplyEmail" in "1")
			 echo "email a single business"
			 #code to email a single business
                         ;;
                   "2") echo "email all businesses"
			#code to email all businesses
                       ;;
                   "q") #exit the emailing of businesses
                          
		       ;;
                    *) echo "invalid option"
                       waitAndClear #wait and clear the display to aid with less clutter
                       ;;
     esac
   done
}
function waitAndClear #function to clear the display after 1 second
{
   sleep 1
   clear
}
while :
do
  cat <<EOF
 
  Welcome. Please Choose from one of the following
  (1) "Add a new Business"
  (2) "Remove an existing Business"
  (3) "Search for a Business"
  (4) "E-mail Business(es)"
  (q) "quit application" 
  Enter a number:
EOF
  #The quit option was given for ergonomics
 read  Reply
 case "$Reply" in "1")
                       ./AddBiz #call the AddBiz script in order to add a business
                       ;;
                  "2") ./RmBiz         #remove an existing business by calling the RmBiz script
                       ;;
                  "3")./FindBiz #find an exisiting business(es) by calling the FindBiz script
                       ;;
                  "4")emailBusiness
		       #email business(es) from the address book
                         ;;
                  "q") echo "Goodbye and thanks"
                       exit
                       ;;
                  *) echo "invalid option"
                       waitAndClear #wait and clear the display to aid with less clutter
                       ;;
     esac
  sleep 1
done

#ToDo: add coding to link the main menu with RmBiz
#ToDo: add coding to link the main menu with emailing one or many businesses
#ToDo: clear up and add commenting and indentation
#ToDo: allow a user to reurn to the main menu at any point

