#!/bin/bash
#removal of business script file
#ToDo: add coding to remove a business based upon business name or contact name
#Todo: add commenting on the file
#Todo: when removing the  business information from the file add it to a deleted file (to be able to review deleted information
searchByBusiness(){
    echo "Please enter the business name"
    read searchparm
    result=`grep -i -n $searchparm BusinessDetails` #move to to being a awk/sed lookup
    echo $result
    sleep 0.5 #wait 0.5 seconds
    echo "which line number do you wish to delete, or q to quit"
    read line
    if [ "$line" == "q" ]  
    then
	: #do nothing
    else
       sed -i "$line"'d' BusinessDetails
       echo "Business deleted"
       fi
    } 
while :
do

  cat <<EOF
 
  Please choose to remove a Business based upon:
  (1) "Business name"
  (2) "Business contact"
  (q) "return to main menu" 
  Please make a selection:
EOF
  #The quit option was given for ergonomics
 read  Reply
 case "$Reply" in "1") searchByBusiness
		  #find business by business name
		       #add functionality
                       ;;
                   "2") #find business by contact name
		       #add functionality
                       ;;
                  "q") echo "back to the main menu"
                       exit
                       ;;
                  *) echo "invalid option"
                       ;;
     esac
  sleep 1
done
